/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bimbel;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author admin
 */
public class form_pembayaran extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    

    /**
     * Creates new form form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
        otomatis();
        datatabel();
         b_hapus.setVisible(false);
         cancel.setVisible(false);
         warna_header1();
         warna_header();
         
         
       
    }
    protected void mati(){
        tagihan.setEnabled(false);
        tunggakan.setEnabled(false);
        status.setEnabled(false);
        nobayar.setEnabled(false);
        t_tanggal.setEnabled(false);
        nama_siswa.setEnabled(false);
    }
    protected void Kosong(){
        lama_belajar.setText("");
        nama_siswa.setText("");
        tagihan.setText("");
        nominal.setText("");
        tunggakan.setText("");
        status.setText("");
        
    }
    //Tabel
    protected void datatabel(){
             
        Object [] Baris = {"No Transaksi","ID Siswa", "Nama Siswa","Jenis Kelas","Lama Belajar","Tanggal",
            "Tagihan","Jumlah Bayar","Tunggakan","Status"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelbayar.setModel(tabmode);
        TablePembayaran.setModel(tabmode);
        
         String sql = "SELECT p.no_pembayaran, p.id_siswa, s.nama_siswa, p.Jenis_kelas, p.lama_belajar, "
                    + "p.tgl, p.Tagihan, p.nominal_bayar, p.tunggakan, p.status_pembayaran "
                    + "FROM tabel_pembayaran p "
                    + "JOIN tabel_siswa s ON p.id_siswa = s.id_siswa "
                    +"ORDER BY no_pembayaran ASC";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("no_pembayaran");
                String b = hasil.getString("id_siswa");
                String c = hasil.getString("nama_siswa"); //dari tabel siswa
                String d = hasil.getString("Jenis_kelas");
                String e = hasil.getString("lama_belajar");
                String f = hasil.getString("tgl");
                String g = hasil.getString("Tagihan");
                String h = hasil.getString("nominal_bayar");
                String i = hasil.getString("tunggakan");
                String j = hasil.getString("status_pembayaran");
            
                String[] data={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
       
            } 
            
        }catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error retrieving data: " + ex.getMessage()); 
           
        }
    }
        
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pembayaran = new javax.swing.JPanel();
        Data_Pembayaran = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b_cari = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        b_tambah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbayar = new javax.swing.JTable();
        Pembayaran_siswa = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cancel2 = new javax.swing.JButton();
        b_tambah2 = new javax.swing.JButton();
        tglTransaksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nobayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        t_waktu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nama_siswa = new javax.swing.JTextField();
        id_siswa = new javax.swing.JComboBox<>();
        lama_belajar = new javax.swing.JTextField();
        tagihan = new javax.swing.JTextField();
        nominal = new javax.swing.JTextField();
        tunggakan = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        mapel = new javax.swing.JComboBox<>();
        Hitung = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePembayaran = new javax.swing.JTable();
        b_hapus1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        Pembayaran.setLayout(new java.awt.CardLayout());

        Data_Pembayaran.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("DATA PEMBAYARAN SISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        b_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/cari.png"))); // NOI18N
        b_cari.setText("Cari");
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(255, 255, 153));
        cancel.setText("BATAL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        b_tambah.setBackground(new java.awt.Color(51, 255, 51));
        b_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/add.png"))); // NOI18N
        b_tambah.setText("TAMBAH");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus.setText("HAPUS");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        tabelbayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbayar.setFocusable(false);
        tabelbayar.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelbayar.setRowHeight(38);
        tabelbayar.getTableHeader().setReorderingAllowed(false);
        tabelbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbayarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbayar);

        javax.swing.GroupLayout Data_PembayaranLayout = new javax.swing.GroupLayout(Data_Pembayaran);
        Data_Pembayaran.setLayout(Data_PembayaranLayout);
        Data_PembayaranLayout.setHorizontalGroup(
            Data_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Data_PembayaranLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_cari)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
        );
        Data_PembayaranLayout.setVerticalGroup(
            Data_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Data_PembayaranLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Data_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Data_PembayaranLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Data_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Data_PembayaranLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(Data_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_cari))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );

        Pembayaran.add(Data_Pembayaran, "card2");

        Pembayaran_siswa.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel6.setText("DATA PEMBAYARAN SISWA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancel2.setBackground(new java.awt.Color(255, 255, 153));
        cancel2.setText("BATAL");
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });

        b_tambah2.setBackground(new java.awt.Color(51, 255, 51));
        b_tambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/add.png"))); // NOI18N
        b_tambah2.setText("TAMBAH");
        b_tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambah2ActionPerformed(evt);
            }
        });

        tglTransaksi.setBackground(new java.awt.Color(0, 153, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Bayar");

        nobayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Transaksi");

        t_tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout tglTransaksiLayout = new javax.swing.GroupLayout(tglTransaksi);
        tglTransaksi.setLayout(tglTransaksiLayout);
        tglTransaksiLayout.setHorizontalGroup(
            tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tglTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(nobayar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tglTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tglTransaksiLayout.createSequentialGroup()
                        .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        tglTransaksiLayout.setVerticalGroup(
            tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tglTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tglTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nobayar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_waktu.setBackground(new java.awt.Color(0, 153, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Siswa");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Siswa");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lama Belajar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jenis Bimbel");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tagihan");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nominal Bayar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tunggakan");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status Bayar");

        id_siswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tunggakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunggakanActionPerformed(evt);
            }
        });

        mapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Hitung.setBackground(new java.awt.Color(255, 255, 255));
        Hitung.setText("HITUNG ");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout t_waktuLayout = new javax.swing.GroupLayout(t_waktu);
        t_waktu.setLayout(t_waktuLayout);
        t_waktuLayout.setHorizontalGroup(
            t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_waktuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(t_waktuLayout.createSequentialGroup()
                        .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(id_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(t_waktuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(60, 60, 60))
                            .addGroup(t_waktuLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(nama_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))))
                    .addComponent(lama_belajar)
                    .addComponent(tagihan)
                    .addComponent(nominal)
                    .addComponent(tunggakan)
                    .addComponent(status)
                    .addComponent(mapel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(t_waktuLayout.createSequentialGroup()
                        .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        t_waktuLayout.setVerticalGroup(
            t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_waktuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(t_waktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(id_siswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(lama_belajar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Hitung, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        TablePembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePembayaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablePembayaran);

        b_hapus1.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus1.setText("HAPUS");
        b_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pembayaran_siswaLayout = new javax.swing.GroupLayout(Pembayaran_siswa);
        Pembayaran_siswa.setLayout(Pembayaran_siswaLayout);
        Pembayaran_siswaLayout.setHorizontalGroup(
            Pembayaran_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Pembayaran_siswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pembayaran_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(t_waktu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
            .addGroup(Pembayaran_siswaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(b_tambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pembayaran_siswaLayout.setVerticalGroup(
            Pembayaran_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pembayaran_siswaLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pembayaran_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pembayaran_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pembayaran_siswaLayout.createSequentialGroup()
                        .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );

        Pembayaran.add(Pembayaran_siswa, "card2");

        add(Pembayaran, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
        Object [] Baris = {"No Transaksi","ID Siswa", "Nama Siswa","Jenis Kelas","Lama Belajar","Tanggal Pembayaran",
            "Tagihan","Jumlah Bayar","Tunggakan","Status Pembayaran"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelbayar.setModel(tabmode);
//        TablePembayaran.setModel(tabmode);
        
            // Dapatkan istilah pencarian dari kolom teks
                String searchTerm = tcari.getText();
        
        
           String sql = "SELECT p.no_pembayaran, p.id_siswa, s.nama_siswa, p.Jenis_kelas, p.lama_belajar, p.tgl, "
                        + "p.Tagihan, p.nominal_bayar, p.tunggakan, p.status_pembayaran "
                        + "FROM tabel_pembayaran p "
                        + "JOIN tabel_siswa s ON p.id_siswa = s.id_siswa "
                        + "WHERE s.id_siswa LIKE ? OR s.nama_siswa LIKE ?";
        
            try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    String wildcardTerm = "%" + searchTerm + "%";
                    stat.setString(1, wildcardTerm); // For id
                    stat.setString(2, wildcardTerm); // For nama
            
                    ResultSet hasil = stat.executeQuery();
            
                    // Hapus hasil sebelumnya
            
                    tabmode.setRowCount(0);
                    //Isi tabel dengan hasil
                    boolean hasResults = false;
                       while(hasil.next()){
                           hasResults = true;
                            String a = hasil.getString("no_pembayaran");
                            String b = hasil.getString("id_siswa");
                            String c = hasil.getString("nama_siswa");
                            String d = hasil.getString("Jenis_kelas");
                            String e = hasil.getString("lama_belajar");
                            String f = hasil.getString("tgl");
                            String g = hasil.getString("Tagihan");
                            String h = hasil.getString("nominal_bayar");
                            String i = hasil.getString("tunggakan");
                            String j = hasil.getString("status_pembayaran");
            
                        String[] data={a,b,c,d,e,f,g,h,i,j};
                        tabmode.addRow(data);
                
                        }
            
                    if (!hasResults) {
                            JOptionPane.showMessageDialog(null, "Data tidak ditemukan.");
                        }
            
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                }
    }//GEN-LAST:event_b_cariActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        b_tambah.setEnabled(true);
        b_hapus.setVisible(false);
        cancel.setVisible(false);
        b_tambah.setBackground(Color.green);
//       kosong();
//        aktif();
        otomatis();
    }//GEN-LAST:event_cancelActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here
            Pembayaran.removeAll();
            Pembayaran.repaint();
            Pembayaran.revalidate();

            Pembayaran.add(Pembayaran_siswa);
            mati();
            Tanggal();
            isiComboBox();
            mapel();
            Kosong();
    }//GEN-LAST:event_b_tambahActionPerformed

    private void tabelbayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbayarMouseClicked

    }//GEN-LAST:event_tabelbayarMouseClicked

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        // TODO add your handling code here:
         Pembayaran.removeAll();
         Pembayaran.repaint();
        Pembayaran.revalidate();
                
        Pembayaran.add(Data_Pembayaran);
        Kosong();
        otomatis();
    }//GEN-LAST:event_cancel2ActionPerformed

    private void b_tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambah2ActionPerformed
   try {
    String id = id_siswa.getSelectedItem().toString();

    
    String sqlCari = "SELECT nama_siswa FROM tabel_siswa WHERE id_siswa = ?";
    PreparedStatement cari = conn.prepareStatement(sqlCari);
    cari.setString(1, id);
    ResultSet rs = cari.executeQuery();

    if (!rs.next()) {
        JOptionPane.showMessageDialog(null, "ID Siswa tidak ditemukan.");
        return;
    }

    
    String sql = "INSERT INTO tabel_pembayaran "
               + "(no_pembayaran, id_siswa, Jenis_kelas, lama_belajar, tgl, Tagihan, nominal_bayar, tunggakan, status_pembayaran) "
               + "VALUES (?,?,?,?,?,?,?,?,?)";

    PreparedStatement stat = conn.prepareStatement(sql);
    stat.setString(1, nobayar.getText());
    stat.setString(2, id);
    stat.setString(3, mapel.getSelectedItem().toString());
    stat.setInt(4, Integer.parseInt(lama_belajar.getText()));
    stat.setString(5, t_tanggal.getText());
    stat.setDouble(6, Double.parseDouble(tagihan.getText()));
    stat.setDouble(7, Double.parseDouble(nominal.getText()));
    stat.setDouble(8, Double.parseDouble(tunggakan.getText()));
    stat.setString(9, status.getText());

    stat.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
    nobayar.requestFocus();
    datatabel(); 

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
}


    }//GEN-LAST:event_b_tambah2ActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        double Nominal = Double.parseDouble(nominal.getText());
        double Tagihan = Double.parseDouble(tagihan.getText());
        double Tunggakan = Nominal - Tagihan; 
        tunggakan.setText(String.valueOf(Tunggakan));
        
        if (Tunggakan == 0){
            status.setText("Lunas"); 
        } else if (Tunggakan <= -1) {
            status.setText("Bulum Lunas");   
        } else {
            status.setText(" Kembalian, Rp." +Tunggakan);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void tunggakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunggakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunggakanActionPerformed

    private void TablePembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePembayaranMouseClicked
        // TODO add your handling code here:
        
 
            int bar = TablePembayaran.getSelectedRow();
            if (bar != -1) {
                String a = tabmode.getValueAt(bar, 0).toString();
                String b = tabmode.getValueAt(bar, 1).toString();
                String c = tabmode.getValueAt(bar, 2).toString();
                String d = tabmode.getValueAt(bar, 3).toString();
                String e = tabmode.getValueAt(bar, 4).toString();
                String f = tabmode.getValueAt(bar, 5).toString();
                String g = tabmode.getValueAt(bar, 6).toString();
                String h = tabmode.getValueAt(bar, 7).toString();
                String i = tabmode.getValueAt(bar, 8).toString();
                String j = tabmode.getValueAt(bar, 9).toString();

                nobayar.setText(a);
                
                id_siswa.setSelectedItem(b);
                nama_siswa.setText(c);
                mapel.setSelectedItem(d);
                lama_belajar.setText(e);
              
                t_tanggal.setText(f);
                tagihan.setText(g);
                nominal.setText(h);
                tunggakan.setText(i);
                status.setText(j);

            } else {
                System.out.println("No row selected.");
                JOptionPane.showMessageDialog(null, "Please select a row to edit.");
            } 
    }//GEN-LAST:event_TablePembayaranMouseClicked

    private void b_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapus1ActionPerformed
        // TODO add your handling code here:
         int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql="delete from tabel_pembayaran where no_pembayaran='"+nobayar.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
//                kosong();
                nobayar.requestFocus();
                datatabel();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_b_hapus1ActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql="delete from tabel_pembayaran where no_pembayaran='"+nobayar.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                //                kosong();
                nobayar.requestFocus();
                datatabel();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_b_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data_Pembayaran;
    private javax.swing.JButton Hitung;
    private javax.swing.JPanel Pembayaran;
    private javax.swing.JPanel Pembayaran_siswa;
    private javax.swing.JTable TablePembayaran;
    private javax.swing.JButton b_cari;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_hapus1;
    private javax.swing.JButton b_tambah;
    private javax.swing.JButton b_tambah2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel2;
    private javax.swing.JComboBox<String> id_siswa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lama_belajar;
    private javax.swing.JComboBox<String> mapel;
    private javax.swing.JTextField nama_siswa;
    private javax.swing.JTextField nobayar;
    private javax.swing.JTextField nominal;
    private javax.swing.JTextField status;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JPanel t_waktu;
    private javax.swing.JTable tabelbayar;
    private javax.swing.JTextField tagihan;
    private javax.swing.JTextField tcari;
    private javax.swing.JPanel tglTransaksi;
    private javax.swing.JTextField tunggakan;
    // End of variables declaration//GEN-END:variables
public void otomatis() {
    try {
        Connection conn = new koneksi().connect();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT MAX(no_pembayaran) FROM tabel_pembayaran");

        if (rs.next()) {
            String lastId = rs.getString(1); // Ambil ID terakhir

            if (lastId == null || lastId.equals("")) {
                nobayar.setText("001");
            } else {
                // Misal ID seperti "BYR005"
                String angkaStr = lastId.replaceAll("[^0-9]", ""); // Ambil hanya angka
                int angka = Integer.parseInt(angkaStr) + 1;
                String newId = String.format("%03d", angka); // Hasil: BYR006, dst.
                nobayar.setText(newId);
            }
        } else {
            nobayar.setText("001");
        }
        
        nobayar.setEnabled(false);
        rs.close();
        st.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: >> Ada di" + e.getMessage());
    }
}
//inputan tanggal
    protected void Tanggal(){
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        t_tanggal.setText(kal.format(now));
        t_tanggal.setEnabled(false);
    }
    //combo box untuk siswa
   private void isiComboBox() {
    try {
        Connection conn = new koneksi().connect();
        String query = "SELECT id_siswa, nama_siswa FROM tabel_siswa"; 
        PreparedStatement pst = conn.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        id_siswa.removeAllItems(); 
        id_siswa.addItem(""); // item kosong sebagai default

        while (rs.next()) {
            id_siswa.addItem(rs.getString("id_siswa"));
        }

        // listener untuk combo box
        id_siswa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedId = (String) id_siswa.getSelectedItem();
                if (selectedId != null && !selectedId.isEmpty()) {
                    isiNamaSiswa(selectedId);
                } else {
                    nama_siswa.setText(""); 
                }
            }
        });

        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal isi combo box: " + e.getMessage());
    }
}

// mengisi nama siswa berdasarkan ID
private void isiNamaSiswa(String id) {
    try {
        Connection conn = new koneksi().connect();
        String query = "SELECT nama_siswa FROM tabel_siswa WHERE id_siswa = ?";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, id);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            nama_siswa.setText(rs.getString("nama_siswa"));
        } else {
            nama_siswa.setText("");
        }

        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengambil nama siswa: " + e.getMessage());
    }
}
//combo box mapel
private void mapel() {
    try {
        Connection conn = new koneksi().connect();
        String query = "SELECT mata_pelajaran FROM tabel_jadwal";
        PreparedStatement pst = conn.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        mapel.removeAllItems(); 
        mapel.addItem("");

        while (rs.next()) {
            mapel.addItem(rs.getString("mata_pelajaran"));
        }
        
        // Tambahkan ActionListener untuk menghitung tagihan
        mapel.addActionListener(e ->Tagihan());
        
        rs.close();
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal mengambil mata pelajaran: " + e.getMessage());
    }
}

private void Tagihan() {
    try {
        String selectedMapel = (String) mapel.getSelectedItem();
        
        // Jika tidak ada mapel yang dipilih atau kosong, set tagihan ke 0
        if (selectedMapel == null || selectedMapel.isEmpty()) {
            tagihan.setText("0");
            return;
        }
        
        // Periksa apakah lama_belajar kosong
        if (lama_belajar.getText().trim().isEmpty()) {
            tagihan.setText("0");
            return;
        }
        
        
        double durasi = Double.parseDouble(lama_belajar.getText());
        double hargaPerBulan = 0;

        // Tentukan harga berdasarkan mata pelajaran
        switch(selectedMapel) {
            case "Calistung":
                hargaPerBulan = 400000;
                break;
            case "Bahasa Inggris":
                hargaPerBulan = 500000;
                break;
            case "Matematika":
                hargaPerBulan = 200000;
                break;
            default:
                hargaPerBulan = 0;
        }

        // Hitung total tagihan
        double totalTagihan = hargaPerBulan * durasi;
        
        // Tampilkan hasil (format bisa disesuaikan)
        tagihan.setText(String.valueOf(totalTagihan));
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Masukkan durasi belajar yang valid!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: data belum ada " + e.getMessage());
    }
}
//Warna Untuk Header
 protected void warna_header(){
             tabelbayar.setShowVerticalLines(true);
             tabelbayar.setGridColor(java.awt.Color.GRAY);
          // Ubah warna header 
        javax.swing.table.JTableHeader header = tabelbayar.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
          @Override
         public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,boolean isSelected, boolean hasFocus, int row, int column) {
        java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
         c.setBackground(new java.awt.Color(0, 153, 0)); 
        c.setForeground(java.awt.Color.WHITE);           
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT); 
        c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD, 13f));
        return c;
         }
        });  
    }
 
 // warna header
 protected void warna_header1(){
             TablePembayaran.setShowVerticalLines(true);
             TablePembayaran.setGridColor(java.awt.Color.GRAY);
          // Ubah warna header 
        javax.swing.table.JTableHeader header = TablePembayaran.getTableHeader();
        header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
          @Override
         public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,boolean isSelected, boolean hasFocus, int row, int column) {
        java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
         c.setBackground(new java.awt.Color(0, 153, 0)); 
        c.setForeground(java.awt.Color.WHITE);           
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT); 
        c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD, 13f));
        return c;
         }
        });  
    }
 
  
}
   

