/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bimbel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import sidecode.MenuItem;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/**
 *
 * @author admin
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pmenu = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        putama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        navbar.setBackground(new java.awt.Color(141, 223, 111));
        navbar.setMinimumSize(new java.awt.Dimension(90, 90));
        navbar.setPreferredSize(new java.awt.Dimension(835, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/zafjunior.jpeg"))); // NOI18N

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 619, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 467));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pmenu.setBackground(new java.awt.Color(255, 255, 255));
        pmenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(102, 255, 102)));
        pmenu.setLayout(new javax.swing.BoxLayout(pmenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pmenu);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(255, 255, 255));

        putama.setBackground(new java.awt.Color(255, 255, 255));
        putama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(putama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(putama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(940, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       putama.add(new dash_board());
       putama.repaint();
       putama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel pmenu;
    private javax.swing.JPanel putama;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables

    
    private void execute(){
        
        ImageIcon Icondashboard = new ImageIcon(getClass().getResource("/background/menu_home1.png"));
        ImageIcon IconMaster = new ImageIcon(getClass().getResource("/background/menu1.png"));
       
        //sub item master 
        ImageIcon IconSiswa = new ImageIcon(getClass().getResource("/background/siswa.png"));
        ImageIcon IconPengajar = new ImageIcon(getClass().getResource("/background/pengajar.png"));
        ImageIcon IconJadwal = new ImageIcon(getClass().getResource("/background/menu_nilai.png"));
        
        //sub-item trasaksi
        ImageIcon IconPembayaran = new ImageIcon(getClass().getResource("/background/salary.png"));
        ImageIcon IconPenggajian = new ImageIcon(getClass().getResource("/background/salary.png"));
        ImageIcon IconNilai = new ImageIcon(getClass().getResource("/background/menu_nilai.png"));
        
        
        //SubMaster form Master
        MenuItem Siswa = new MenuItem(null,true,IconSiswa,"Data Siswa",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new form_siswa());
                 putama.repaint();
                 putama.revalidate();
                
            }
        });
        MenuItem Pengajar = new MenuItem(null,true,IconPengajar,"Data Guru",new ActionListener() {
            @Override
             public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new form_guru());
                 putama.repaint();
                 putama.revalidate();
             }
        });
             
             
             
        MenuItem Jadwal = new MenuItem(null,true,IconJadwal,"Jadwal",new ActionListener() {
              @Override
             public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new form_jadwal());
                 putama.repaint();
                 putama.revalidate();
             }
        });
        
        //subMaster Pada form Transaksi
        MenuItem Pembayaran = new MenuItem(null,true,IconPembayaran,"pembayaran",new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new form_pembayaran());
                 putama.repaint();
                 putama.revalidate();
             }

        });
        MenuItem Penggajian = new MenuItem(null,true,IconPenggajian,"penggajian",null);
        
        MenuItem Nilai = new MenuItem(null,true,IconNilai,"Nilai Siswa",new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new form_nilai());
                 putama.repaint();
                 putama.revalidate();
             }
        });
        
        MenuItem dashboard = new MenuItem(Icondashboard,false,null,"Home",new ActionListener() {
            @Override
             public void actionPerformed(ActionEvent e){
                 putama.removeAll();
                 putama.add(new dash_board());
                 putama.repaint();
                 putama.revalidate();
             }
        });
        
        
        //Menu Utama
        MenuItem menuMaster = new MenuItem(IconMaster,false,null,"Master",null,Siswa,Pengajar,Jadwal);
        MenuItem mTransaksi = new MenuItem(IconMaster,false,null,"Transaksi",null,Pembayaran,Penggajian,Nilai);
        MenuItem mReport = new MenuItem(IconMaster,false,null,"Report",null);
        
        
     
        
        addMenu(dashboard,menuMaster,mTransaksi,mReport);
        
    }
    
    
    private void addMenu(MenuItem...menu) {
       for (int i=0; i < menu.length; i++){
            pmenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu){
                addMenu(m);
            }
       }
       pmenu.revalidate();
    }

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
