/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sidecode;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author admin
 */
public class MenuItem extends javax.swing.JPanel {
    
    public ArrayList<MenuItem> getSubMenu() {
      return subMenu;
}
    
    private final ArrayList<MenuItem> subMenu = new ArrayList<>();
    
    private ActionListener act;

    /**
     * Creates new form MenuItem
     */
    public MenuItem(Icon icon, boolean sbm, Icon iconSub, String menuName, ActionListener act,MenuItem...subMenu) {
        initComponents();
        
         lb_icon.setIcon(icon);
        lb_mainmenu.setText(menuName);
        lb_subicon.setIcon(iconSub);
        lb_subicon.setVisible(sbm);
        
        if (act != null){
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMaximumSize(new Dimension (Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension (Integer.MAX_VALUE,45));
        for (int i=0; i < subMenu.length; i++) {
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_icon = new javax.swing.JLabel();
        lb_subicon = new javax.swing.JLabel();
        lb_mainmenu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lb_mainmenu.setText("Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lb_subicon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_subicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if (showing){
            hideMenu();
        } else {
            showMenu();
        }
        if ( act != null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_mainmenu;
    private javax.swing.JLabel lb_subicon;
    // End of variables declaration//GEN-END:variables

    private void hideMenu() {
        new Thread(new Runnable() {
            @Override
            public void run(){
                for (int i = getSubMenu().size() - 1; i >= 0; i--) {
                 sleep();
                 getSubMenu().get(i).setVisible(false);
                 getSubMenu().get(i).hideMenu();
            }
                getParent().repaint();
                getParent().revalidate();
                showing = false;
            }
        }).start();
    }

    private void showMenu() {
       new Thread (new Runnable(){
          @Override
           public void run() {
               for (int i = 0; i < getSubMenu().size(); i++) {
                   sleep();
                   getSubMenu().get(i).setVisible(true);
               }
               showing = true;
               getParent().repaint();
               getParent().revalidate();
           } 
       }).start();
    }
    
private void sleep(){
    try{
        Thread.sleep(20);
    } catch (Exception e){
        
    }
}
}


